//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.FoxServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FoxServer.IFoxCtrl")]
    public interface IFoxCtrl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxCtrl/DoWork", ReplyAction="http://tempuri.org/IFoxCtrl/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxCtrl/DoWork", ReplyAction="http://tempuri.org/IFoxCtrl/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxCtrl/GetFoxData", ReplyAction="http://tempuri.org/IFoxCtrl/GetFoxDataResponse")]
        System.Data.DataTable GetFoxData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoxCtrl/GetFoxData", ReplyAction="http://tempuri.org/IFoxCtrl/GetFoxDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetFoxDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoxCtrlChannel : TestWeb.FoxServer.IFoxCtrl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoxCtrlClient : System.ServiceModel.ClientBase<TestWeb.FoxServer.IFoxCtrl>, TestWeb.FoxServer.IFoxCtrl {
        
        public FoxCtrlClient() {
        }
        
        public FoxCtrlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoxCtrlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoxCtrlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoxCtrlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable GetFoxData() {
            return base.Channel.GetFoxData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetFoxDataAsync() {
            return base.Channel.GetFoxDataAsync();
        }
    }
}
