//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.UserServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServer.IUserCtrl")]
    public interface IUserCtrl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCtrl/DoWork", ReplyAction="http://tempuri.org/IUserCtrl/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCtrl/DoWork", ReplyAction="http://tempuri.org/IUserCtrl/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCtrl/GetUserData", ReplyAction="http://tempuri.org/IUserCtrl/GetUserDataResponse")]
        System.Data.DataTable GetUserData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserCtrl/GetUserData", ReplyAction="http://tempuri.org/IUserCtrl/GetUserDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetUserDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserCtrlChannel : TestWeb.UserServer.IUserCtrl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserCtrlClient : System.ServiceModel.ClientBase<TestWeb.UserServer.IUserCtrl>, TestWeb.UserServer.IUserCtrl {
        
        public UserCtrlClient() {
        }
        
        public UserCtrlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserCtrlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserCtrlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserCtrlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable GetUserData() {
            return base.Channel.GetUserData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetUserDataAsync() {
            return base.Channel.GetUserDataAsync();
        }
    }
}
